server:
  port: 8086
  servlet:
    context-path: /journalsm
spring:
  data:
  #    username: myjournaluser
  #    password: mypassword
  mongodb:
    uri: ${cred}
    port: 27017
    host: localhost
    database: journaldb
    auto-index-creation: true

    logging:
      level:
        com:
          sm:
            journalApp: DEBUG




