server:
  port: 8086
  servlet:
    context-path: /journalsm
spring:
  data:
  #    username: myjournaluser
  #    password: mypassword
  mongodb:
    uri: mongodb+srv://subhammathpal:IZPuVm5tKNFwFa11@cluster0.tts9y2l.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    port: 27017
    host: localhost
    database: journaldb
    auto-index-creation: true

    logging:
      level:
        com:
          sm:
            journalApp: DEBUG




